### ISSUE TITLE
[error] GenServer #PID<0.763.0> terminating ** (KeyError) key :id not found in: nil

### ISSUE THREAD

**Issue by 973398769** [cbh123/stickerbaker#10]
<img width="1195" alt="Screenshot 2024-03-13 at 5 58 10 PM" src="https://github.com/cbh123/stickerbaker/assets/50310195/18a8bf45-d431-4efd-ba94-fc02c58c30c1">
Hi @cbh123 , I want to run the project in my local machine, but encounter this error logs, Could you give me some suggestions to tackle this issue? Many thanks!

**Comment by cbh123** [comment]
Ah you can ignore that — that background process is failing in the background because there are no stickers to create embeddings of. You can also comment out these two lines in `application.ex` to turn them off:

<img width="553" alt="Screenshot 2024-03-13 at 12 10 14 PM" src="https://github.com/cbh123/stickerbaker/assets/14149230/545e535e-be8d-4e7b-b195-1601c8ff906a">
